Fix distributions script and run all tests while distributing

diff --git a/createDistributions b/createDistributions
--- a/createDistributions
+++ b/createDistributions
@@ -1,10 +1,12 @@
 #!/bin/bash
 
 # set overrides for setlX launcher script
-export OVERRIDE_setlXJarDirectory="$PWD/src/"
+export OVERRIDE_setlXJarDirectory="$PWD/interpreter/"
 
 # other locations for tests
-setlXlaunchScript="$PWD/src/setlX"
+setlXlaunchScript="$OVERRIDE_setlXJarDirectory/setlX"
+
+cd "$OVERRIDE_setlXJarDirectory"
 
 # clean the interpreter source
 echo "=> Cleaning the setlX interpreter's source ..."
@@ -27,7 +29,7 @@ fi
 
 # ensure some files use Windows line-endings
 if [ $(which unix2dos > /dev/null 2>&1; echo $?) -eq 0 ]; then
-    unix2dos src/setlX.cmd
+    unix2dos "$OVERRIDE_setlXJarDirectory/setlX.cmd"
 fi
 
 # get version from executable (jar)
@@ -35,16 +37,29 @@ version=$("$setlXlaunchScript" --version | head -n 1)
 
 # warn if current release is not tagged in git
 gitWarning=""
-if [ -d ".git" -a $(which git >/dev/null 2>&1; echo $?) -eq 0 ]
+if [ -d "../.git" -a $(which git >/dev/null 2>&1; echo $?) -eq 0 ]
   then
-    if [ $(git tag | grep -c "v$version") -ne 1 ]
-      then
+    if [ $(git tag | grep -c "v$version") -ne 1 ]; then
         gitWarning="WARNING: Version number of created distribution is not tagged in git!"
         version="$version.experimental"
-    elif [ $(git diff --name-only "v$version" | wc -l) -gt 0 ]
-      then
+    elif [ $(git diff --name-only "v$version" | wc -l) -gt 0 ]; then
         gitWarning="WARNING: Source differs from commit tagged with 'v$version' in git!"
         version="$version.experimental"
+    fi
+else
+    gitWarning="WARNING: Build version could not be verified (git or git-repo missing)"
+fi
+
+cd ..
+
+# run tests
+if [ "$1" != "noTests" ]; then
+    echo "=> Testing the setlX interpreter ..."
+    ./test_all_examples; rc=$?
+    if [ $rc -ne 0 ]; then
+        echo "=> Errors occured while testing the interpreter."
+        echo "=> Distribution stopped!"
+        exit 1
     fi
 fi
 
@@ -141,7 +156,7 @@ rm -f diff.*.result
 # create binary only zip
 echo -n "=> Creating binary only distribution ... "
 mkdir -p zipContents
-cp changelog.txt manual.pdf tutorial.pdf src/setlX src/setlX.cmd src/setlX.jar src/setlX-gfx.jar zipContents/.
+cp changelog.txt manual.pdf tutorial.pdf $OVERRIDE_setlXJarDirectory/setlX $OVERRIDE_setlXJarDirectory/setlX.cmd $OVERRIDE_setlXJarDirectory/setlX.jar $OVERRIDE_setlXJarDirectory/setlX-gfx.jar zipContents/.
 cp -r syntax_highlighting zipContents/.
 cd zipContents; zip -qr "../$binOnly.zip" . ; cd ..
 rm -rf zipContents
@@ -163,11 +178,13 @@ rm -rf zipContents
 echo "done"
 
 # remove the jars
+cd "$OVERRIDE_setlXJarDirectory"
 ant dist-clean
+cd ..
 
 # create development zip
 echo -n "=> Creating development kit ... "
-zip -qr "$devel.zip" . -x \*.zip \*.git\*
+zip -qr "$devel.zip" . -x \*.zip \*.git\* \*.idea\* \*.iml
 echo "done"
 
 if [ -n "$gitWarning" ]
