add font and update Makefile for tutorial

diff --git a/createDistributions b/createDistributions
--- a/createDistributions
+++ b/createDistributions
@@ -72,6 +72,29 @@ else
     exit 1
 fi
 
+# goto tutorial's source
+cd ../Tutorial
+
+# clean the documentation source
+echo "=> Cleaning the tutorial's source ..."
+make dist-clean
+
+# make tutorial
+echo "=> Rebuilding the tutorial ..."
+make
+if [ -f tutorial.pdf ]
+  then
+    # move the finished PDFs where they belong
+    mv -f *.pdf ../.
+    # clean it up again
+    make dist-clean
+    echo "=> The tutorial was build correctly."
+else
+    echo "=> Building the tutorial failed ..."
+    # break
+    exit 1
+fi
+
 # go to project root
 cd ..
 
